title: Adam Khan
logo: 1736478922877January2025Adam.png
description: Software Developer graduate with hardware experience from Techy
show_downloads: true
theme: jekyll-theme-midnight
#remote_theme: pages-themes/midnight@v0.2.0
#plugins:
#- jekyll-remote-theme
